FROM mdillon/postgis:10-alpine
ENV POSTGRES_DB=dhis2 POSTGRES_USER=dhis POSTGRES_PASSWORD=dhis

# ADD ./seed/sierra_leone_demo.sql /tmp/seed.sql
# RUN /etc/init.d/postgresql start && /usr/bin/psql -a < /tmp/seed.sql && /etc/init.d/postgresql stop